### PR TITLE
fix: :bug: give alert on load if either file picker is not supported

### LINKED ISSUE #28: Handle lack of support for file system access more gracefully
Currently if the user is on a browser that doesn't support the files system access API, task aggregator will show the open/ create file dialog but neither button will work. I think it should either display a message explaining that the browser is unsupported or it should fall back to another storage technique.

### PR DESCRIPTION
**Pull request by coxender**
Also disables open file and create file buttons.
tested on Firefox.

fixes #28

### CODE REVIEW

File: src/file.ts [hunk 1]
```diff
@@ -22,10 +28,16 @@ if (url.searchParams.has("from-file") && "launchQueue" in window && "files" in L
   dialog.showModal();
 }
 
+if (!("showOpenFilePicker" in window) || !("showSaveFilePicker" in window)) {
+  openButton.disabled = true;
+  createButton.disabled = true;
+  alert("File tools are not supporeted by current browser.");
```
Comment (nstringham) [inline src/file.ts:34]: It might be better to be more specific so that users can figure out what browsers are supported.

File: src/file.ts [hunk 2]
```diff
@@ -3,11 +3,17 @@ import { TaggFile, isValidTaggFile, JSON_SCHEMA, Tag, Task } from "./types";
 
 const dialog = document.querySelector("#startup-dialog") as HTMLDialogElement;
 const openButton = dialog.querySelector("#open-button") as HTMLButtonElement;
-const createButton = dialog.querySelector("#create-button") as HTMLButtonElement;
+const createButton = dialog.querySelector(
```
Comment (nstringham) [inline src/file.ts:6]: See #31

File: src/file.ts (hunk 1 above)
Comment (nstringham) [inline src/file.ts:34]: should be spelled "supported"

File: src/file.ts [hunk 3]
```diff
@@ -22,10 +28,16 @@ if (url.searchParams.has("from-file") && "launchQueue" in window && "files" in L
   dialog.showModal();
 }
 
+if (!("showOpenFilePicker" in window) || !("showSaveFilePicker" in window)) {
+  openButton.disabled = true;
```
Comment (nstringham) [inline src/file.ts:32]: It might be better to avoid opening the modal in the first place rather than opening it and disabling the buttons.  We could even open a different modal with a link to a website that lists which browsers support the feature instead of using the default alert that can be dismissed by the user and doesn't align with our website style.

**Review by nstringham — COMMENTED** [review]
This looks great. Good job Chiara. I have a few things that could be improved but none of them are very important so I'd be fine merging it as is.

File: src/file.ts (hunk 1 above)
Comment (coxender) [reply src/file.ts:34]: Ah good point. I have it in the error message but not where the user is

Comment (coxender) [reply src/file.ts:34]: Yeah...
